### ISSUE TITLE
[BUG] Broken build on Unity 2021.2b beta due to Android build constraint

### ISSUE THREAD

**Issue by shortenda** [Unity-Technologies/com.unity.webrtc#490]
**Describe the bug**
I'm getting this error message when using this library with 2021.2b beta:

"Library\PackageCache\com.unity.webrtc@2.4.0-exp.3\Editor\BuildProcessor.cs(31,69): error CS0619: 'AndroidSdkVersions.AndroidApiLevel21' is obsolete: 'Minimum supported Android API level is 22 (Android 5.1 Lollipop). Please use AndroidApiLevel22 or higher'"

Note that this issue is not only present when building for android, but is also present in the editor when a project is not set up for android.

**To Reproduce**
1. Install 2021.2b beta
2. Install com.unity.webrtc
3. See build error in console

**Expected behavior**
Library should be updated to support beta (since this is a trivial fix)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Unity Version: 2021.2b
 - Package version 2.4.0-exp.3

**Comment by karasusan** [comment]
Thanks for your report.
This issue has already been fixed but it will be released in few weeks.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/448

**Comment by shortenda** [comment]
My apologies, thanks!
