### ISSUE TITLE
[BUG]: '__debug' file not found while building the plugin on MAC and xcode15

### ISSUE THREAD

**Issue by AnandMWio** [Unity-Technologies/com.unity.webrtc#1030]
### Package version

3.0.0-pre.7

### Environment

```markdown
* OS:macOS Sonoma 4.4.1
* XCode 15
```

### Steps To Reproduce

Clone the repo
try to run Build_plugin_mac.sh 
it says then no Plugin~/webrtc folder found under BuildScripts~
then i copied the plugin~ folder from the repo to BuildScripts~
process goes further and throws this error

### Current Behavior

`/BuildScripts~/Plugin~/libcxx/debug.cpp:21:10: fatal error: 
      '__debug' file not found
#include "__debug"
         ^~~~~~~~~
1 error generated.
`

### Expected Behavior

it generates plugin for mac device.

### Anything else?

i wanted to build custom version of webrtc, but before that i want to understand normal flow and build process of webrtc , but that is also not working for me:(

**Comment by devluz** [comment]
I just ran into the same issue. I tried to rebuild the repository using a clean Xcode 15.4 installation and I get the same error. 
It does work using my old Xcode 15.2 folder though. It contains the __debug file here:
./Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__debug

The new Xcode 15.4 simply does not have this file. 

I am curios what is the purpose of the __debug is? 

As a workaround I tried simply removing the inclusion and so far everything appears to build.
